### ISSUE TITLE
Compilation error when if `NVTX_DISABLE` is defined

### ISSUE THREAD

**Issue by AntoineFroger** [NVIDIA/NVTX#38]
The following code fails to compile with GCC 8.4.0.

```
#define NVTX_DISABLE
#include <nvtx3/nvtx3.hpp>
int main() {}
```

Compilation error:

```
/home/afroger/dev/projects/NVTX/cpp/include/nvtx3/nvtx3.hpp: In function ‘nvtx3::v1::range_handle nvtx3::v1::start_range(const Args& ...)’:
/home/afroger/dev/projects/NVTX/cpp/include/nvtx3/nvtx3.hpp:1979:9: error: ‘first’ was not declared in this scope
   (void)first;
         ^~~~~
```
