### PR TITLE
cpp: fix error when `NVTX_DISABLE` is defined

### LINKED ISSUE #38: Compilation error when if `NVTX_DISABLE` is defined
The following code fails to compile with GCC 8.4.0.

```
#define NVTX_DISABLE
#include <nvtx3/nvtx3.hpp>
int main() {}
```

Compilation error:

```
/home/afroger/dev/projects/NVTX/cpp/include/nvtx3/nvtx3.hpp: In function ‘nvtx3::v1::range_handle nvtx3::v1::start_range(const Args& ...)’:
/home/afroger/dev/projects/NVTX/cpp/include/nvtx3/nvtx3.hpp:1979:9: error: ‘first’ was not declared in this scope
   (void)first;
         ^~~~~
```

### PR DESCRIPTION
**Pull request by AntoineFroger**
Closes #38

### CODE REVIEW

**Review by jrhemstad — APPROVED** [review]

**Comment by jcohen-nvidia** [comment]
Good catch.
